name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    name: Compile Gulp
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Check Dependencies
        run: npm install
      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: compile
    timeout-minutes: 10

    name: Deploy to GitHub Pages
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: bash build.sh ${GITHUB_SHA::7}
